services:
  apache:
    build:
      context: docker/php
      dockerfile: php.Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/blog

  mysql:
    image: mysql
    env_file:
      - ./docker/mysql/mysql.env

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

  composer:
    build:
      context: docker/composer
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/blog

  artisan:
    build:
      context: docker/php
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/blog
    entrypoint: [ "php", "/var/www/blog/artisan" ]
